### ISSUE TITLE
Chapter 12, differences in book and repository code

### ISSUE THREAD

**Issue by koted0** [ehmatthes/pcc#102]
on page 248 after we initialized class Ship.py, I have some troubles because in book inside alien_invasion.py file we sending to Ship() class object **screen**, but we dont have any objects screen and program gives error
its 100% book code in my IDE(Except for translation of comments from Russian to English)
![image](https://user-images.githubusercontent.com/47426673/104066802-124fad80-5213-11eb-8d49-4749007507b2.png)

![image](https://user-images.githubusercontent.com/47426673/104066862-28f60480-5213-11eb-8075-9cdaac3195f8.png)

P.S. sorry for bad English, Im from Russia.

**Comment by wysiwyg-git** [comment]
Try to change "screen" to "self" on the 19 string. So you should have "self.ship = Ship(self)"

**Comment by ehmatthes** [comment]
There's a full explanation of why `self` is passed to `Ship` [here](https://ehmatthes.github.io/pcc_2e/reader_questions/ship_self/). Also, this is the repository for the first edition of the book, but you're working from the second edition. The repository for the second edition is [here](https://github.com/ehmatthes/pcc_2e).
