### ISSUE TITLE
Can't get ship to move

### ISSUE THREAD

**Issue by dbonomo** [ehmatthes/pcc#19]
Hey Eric, I'm following the instructions in chapter 12 and I can't seem to get my ship to move at all. Do I need to do anything to "capture" the keyboard input while checking the code running in the game screen? I can see the key codes being printed out in the console, but the screen does not update. I even tried using the code you've provided for the restore point with no luck. 
I did pre-install the audio components you mention that are optional at the beginning of the project. Is there something I need to do to have this script work with those components installed?
My code thus far: https://github.com/dbonomo/fun-with-pygame

**Comment by ehmatthes** [comment]
I'm sorry, I just saw this! Did you ever sort out the issue? If not, I'm happy to help.

**Comment by CDarnielle** [comment]
I'm seeing the same thing. @dbonomo, what OS and version of python are you running? I'm wondering if what we are seeing is this issue. https://bitbucket.org/pygame/pygame/issues/203/window-does-not-get-focus-on-os-x-with

**Comment by ehmatthes** [comment]
Hi @CDarnielle, I think this probably is an OS X issue. I'll take a closer look at this tonight or this weekend and get back to you. A few readers have mentioned this over the past year, but I believe everyone's been able to sort it out.

**Comment by ehmatthes** [comment]
@CDarnielle, what version of Python are you using? Are you using a virtual environment?

**Comment by CDarnielle** [comment]
macOS Sierra (10.12.2), home-brew install of python3 (Python 3.5.2), virtualenv (15.1.0). I went ahead and reset using the builtin python virtual environments in 3.3+ described in PEP405 (https://www.python.org/dev/peps/pep-0405/) versus virtualenv. This works as expected and keys are working as expected.

**Comment by ehmatthes** [comment]
So just to confirm @CDarnielle, everything's working for you now?

**Comment by CDarnielle** [comment]
yes that's correct.

**Comment by surfcanarias** [comment]
Hi Guys,
I'm still struggling to have my ship move and fire bullets. I'm using MAC OSX Sierra.
Could you please describe what shall I do to have it working properly (providing the code has no error ;-) )?
MThanks!

![screen shot 2017-03-31 at 11 58 12](https://cloud.githubusercontent.com/assets/10373303/24545899/6759e48e-1609-11e7-84ba-e85d604052ed.jpg)

**Comment by skerker** [comment]
Looks like I have the same issue - no movement with the right arrow key.  I'm running macOS sierra 10.12.4.   Using Python 3.5.1 |Anaconda custom (x86_64).  Wondering if anyone has any suggestions.  Thanks!

**Comment by ehmatthes** [comment]
Hi @surfcanarias, @skerker. Sorry to be absent from this thread for a while. @surfcanarias, did you ever get this sorted out?

@skerker, does your Pygame window have focus? I see the terminal in front of the pygame window. If you click in the Pygame window, do the keys start working?

**Comment by skerker** [comment]
In my case, I click on the window and I see the ship in the middle, but the right arrow key doesn't do anything except in my terminal window I see  ^[[C^[[C^[[C^[[C^[[C^[[C^[[C

I can press the red button and close the program - so at least a bunch of things are working OK.  I also tried some of the examples in the pygame folder and was able to find something where my trackpad functions - the program is called "scroll.py".  So I know that some keyboard input is working.

thanks for your help.

**Comment by surfcanarias** [comment]
Same as me. This is happening on my MAC OS X (Sierra) with ANY key, spacebar included. I double checked the code on my Windows PC and it works perfectly, so no coding errors.

**Comment by ehmatthes** [comment]
Are either of you working inside a virtual environment?

**Comment by ehmatthes** [comment]
I think [this pygame issue](https://bitbucket.org/pygame/pygame/issues/203/window-does-not-get-focus-on-os-x-with) is the most relevant description I've seen of the issue you're both facing.  Have either of you had issues with matplotlib at all?

**Comment by skerker** [comment]
I have python installed using conda.   And then used pip to install pygame.

**Comment by skerker** [comment]
matplotlib works fine for me - but I do that all through a jupyter notebook

**Comment by skerker** [comment]
I got it working.   I deactivated all my conda environments.  And then
installed pygame under python 3.6.1

both my base python 2.7.13 and 3.6.1  are in   /usr/local/bin/python3

then I simply installed pygame and it worked!   Now I can move the rocket
ship to the right.  And this test game worked too.

python3 -m pip install pygame --user

python3 -m pygame.examples.aliens

**Comment by skerker** [comment]
As a test, I installed a python 3.6.1 environment using conda, installed
pygame, and now the keyboard doesn't work.

so pygame only works for me when I have /usr/local/bin/python3  but not
when I have python installed here:

/anaconda/envs/py36/bin/python

**Comment by FROLELPA** [comment]
Hi, I still have problems with moving the ship. Would you be able to help me?

**Comment by Theaxiom** [comment]
This issue is caused by running `pygame` in a `virtualenv`, you can solve this simply by running the application in your `userspace` or global environment.

**Comment by krec-kiran** [comment]
Are there any specific steps, which could be followed for pygame window focus problems on mac. Please let us know. The alien ship project does not work without solving this window focus issue

**Comment by Theaxiom** [comment]
I resolved it by not using a virtualenv for development. I ran it in the global userspace.

**Comment by wtbsw** [comment]
running alien_invasion.py using pythonw in terminal works.
it is -- pythonw alien_invasion.py 
original solution
https://github.com/pygame/pygame/issues/359#issuecomment-332188010

**Comment by muralidharkuruva** [comment]
Cannot move the ship right and left using the arrow keys in Chapter 12.
IDE - Pycharm CE
Python 3
MACOS Sierra

New to Python world and working on the exercises from the python crash course 3 book.
I understand this is an old problem, but I am not finding a solution. 
Someone help me in fixing this by providing the link to the solution.

**Comment by ehmatthes** [comment]
@muralidharkuruva, where can we see your code?

**Comment by muralidharkuruva** [comment]
@ehmatthes, Thanks for responding.
I got the code working, it was a typo error.

            if event.type == pygame.QUIT:
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                if **event.key** == pygame.K_RIGHT: 
                    self.ship.moving_right = True
                elif **event.key** == pygame.K_LEFT:
                    self.ship.moving_left = True

            elif event.type == pygame.KEYUP:
                if **event.key** == pygame.K_RIGHT:
                    self.ship.moving_right = False
                elif **event.key** == pygame.K_LEFT:
                    self.ship.moving_left = False

Earlier I coded _event.type_ instead of **event.key**

The code is working now, will continue working on the project.

**Comment by djoshi6** [comment]
I'm having the exact same issue. I don't know how to run my program from a virtual environment in a global userspace. Everything is the same as is in the book, my ship is not moving when prompted to by the right/left arrow keys. Using OS X Sierra.

**Comment by ehmatthes** [comment]
@djoshi6 I posted a response on [r/learnpython](https://www.reddit.com/r/learnpython/comments/cjsszl/python_crash_course/), where you also posted your question.

**Comment by thegtzz** [comment]
> @ehmatthes, Thanks for responding.
> I got the code working, it was a typo error.
> 
> ```
>         if event.type == pygame.QUIT:
>             sys.exit()
>         elif event.type == pygame.KEYDOWN:
>             if **event.key** == pygame.K_RIGHT: 
>                 self.ship.moving_right = True
>             elif **event.key** == pygame.K_LEFT:
>                 self.ship.moving_left = True
> 
>         elif event.type == pygame.KEYUP:
>             if **event.key** == pygame.K_RIGHT:
>                 self.ship.moving_right = False
>             elif **event.key** == pygame.K_LEFT:
>                 self.ship.moving_left = False
> ```
> 
> Earlier I coded _event.type_ instead of **event.key**
> 
> The code is working now, will continue working on the project.

Had the same issue with movement because of event.type instead of **event.key**

**Comment by gpetty002** [comment]
> > @ehmatthes, Thanks for responding.
> > I got the code working, it was a typo error.
> > ```
> >         if event.type == pygame.QUIT:
> >             sys.exit()
> >         elif event.type == pygame.KEYDOWN:
> >             if **event.key** == pygame.K_RIGHT: 
> >                 self.ship.moving_right = True
> >             elif **event.key** == pygame.K_LEFT:
> >                 self.ship.moving_left = True
> > 
> >         elif event.type == pygame.KEYUP:
> >             if **event.key** == pygame.K_RIGHT:
> >                 self.ship.moving_right = False
> >             elif **event.key** == pygame.K_LEFT:
> >                 self.ship.moving_left = False
> > ```
> > 
> > 
> > Earlier I coded _event.type_ instead of **event.key**
> > The code is working now, will continue working on the project.
> 
> Had the same issue with movement because of event.type instead of **event.key**

SAME HERE. I didn't even type event.type or event.key. I somehow missed both of them and decided to just write in "event". I was worried for a second that the problem was my virtual environment. Comparing code with others is a must!
