### ISSUE TITLE
python_repos.py

### ISSUE THREAD

**Issue by west3405** [ehmatthes/pcc#21]
code encounters error on line 46
AttributeError: 'NoneType' object has not attribute 'decode'

I think this error may be due to non-standard ASCII characters in the repo_dict descriptions.

**Comment by west3405** [comment]
The code below fixed the issue.

#line 20
plot_dict = {
        'value': int(repo_dict['stargazers_count']),
        'label': str(repo_dict['description']),
        'xlink': repo_dict['html_url'],
        }
    plot_dicts.append(plot_dict)

**Comment by ehmatthes** [comment]
Sorry for not responding earlier, I just saw this issue. One of the most-starred projects has been removed from GitHub, but the project still shows up in the results. The description is returned as None, which causes an error.

There's a short writeup about the issue, and a more complete update for the code, at http://ehmatthes.github.io/pcc/chapter_17/README.html.
