### ISSUE TITLE
don't draw aliens in screen

### ISSUE THREAD

**Issue by FarAwaytarget** [ehmatthes/pcc#22]
hello,I have a question, 
in "def update_screen(ai_settings, screen, ship, aliens, bullets):"  function ,
I write     aliens.draw(screen)  this one fuc， but the programing  still can't running.
the following is error:

Traceback (most recent call last):
  File "alien_invasion.py", line 32, in <module>
    run_game()
  File "alien_invasion.py", line 31, in run_game
    gf.update_screen(ai_settings, screen, ship, alien, bullets)
  File "/Users/Wzd/Documents/github/alien_invasion/game_functions.py", line 35, in update_screen
    aliens.draw(screen)
AttributeError: 'Alien' object has no attribute 'draw'

can you help me ,thanks ,I 'm reading your book, it's good!

**Comment by globax89** [comment]
Good time! Sorry, I'm not the author of the book Eric Matthes (Python course). Yes, the book is good. She came to me and seemed not bad. Unfortunately, I did not see you in the repository of the source code of this module.

**Comment by FarAwaytarget** [comment]
thanks ,I'm inside the book learning write code.
sorry,this is my fault, the author's code is right. parameter error,
When the method is called, I wrote less of a 's'.  I'm so sorry!

**Comment by globax89** [comment]
Good luck!)
