### ISSUE TITLE
python_repos.py test

### ISSUE THREAD

**Issue by mbabaian** [ehmatthes/pcc#27]
I noticed that in your guide to testing the status code for python_repos.py, you have "import python_repos_for_testing as pr". When I used that, python gave me an error that there's no such module. So I changed it to "import python_repos as pr", and that seemed to work. The test ran without errors. 
Was it OK to make that change, or did I mess up the unittest?

Thanks!

**Comment by ehmatthes** [comment]
I named that file python_repos_for_testing.py, so I could have a separate file python_repos.py that matches the listing in chapter 17. The import statement in your version of test_python_repos.py should match the name you've given to the file that contains the code you want to test.
