### ISSUE TITLE
Chapter 10: alice.py (Python 2.7.12)

### ISSUE THREAD

**Issue by kaotikus** [ehmatthes/pcc#28]
Code review: Exceptions (IOError vs FileNotFoundError) under Python 2.7.12

Able to run alice.py via:
`
filename = 'alice.txt'
try:
    with open(filename) as f_obj:
        contents = f_obj.read()
except IOError:
    msg = "Sorry, the file " + filename + " does not exist."
    print(msg)
`

System: MAC OS 10.11.6, Anaconda Python REPL

**Comment by ehmatthes** [comment]
Thanks for letting me know about this.
