### ISSUE TITLE
Pygal Bar Graphs & Maps Aren't Interactive

### ISSUE THREAD

**Issue by rsch215** [ehmatthes/pcc#29]
I am having an issue with chapters 15 and 16. When I open a map or bar graph in MS Edge and hover over a par or country, the outline darkens but I do not get any of the info that should be showing (ie. Country code and population).

Below is an example of the code I have for world_population.py.

import json
from pygal.maps.world import World
from pygal.style import RotateStyle
from country_codes import get_country_code

# Load the data into a list.
filename = 'population_data.json'
with open(filename) as f:
    pop_data = json.load(f)
    
# Build a dictionary of population data.
cc_populations = {}
for pop_dict in pop_data:
    if pop_dict['Year'] == '2010':
        country_name = pop_dict['Country Name']
        population = int(float(pop_dict['Value']))
        code = get_country_code(country_name)
        if code:
            cc_populations[code] = population
            
# Group the countries into 3 population levels.
cc_pops_1, cc_pops_2, cc_pops_3, = {}, {}, {}
for cc, pop in cc_populations.items():
    if pop < 10000000:
        cc_pops_1[cc] = pop
    elif pop < 1000000000:
        cc_pops_2[cc] = pop
    else:
        cc_pops_3[cc] = pop
        
# See how many countries are in each level.
print(len(cc_pops_1), len(cc_pops_2), len(cc_pops_3))

          
wm = World()
wm.force_uri_protocol = 'http'
wm.title = 'World Population in 2010, by Country'
wm.add('0-10m', cc_pops_1)
wm.add('10m-1bn', cc_pops_2)
wm.add('>1bn', cc_pops_3)

wm.render_to_file('World Population.svg')

**Comment by mbabaian** [comment]
Have you tried viewing the charts in Chrome? I had the same issue with Edge but it works for me on Chrome. Hope this helps.

**Comment by rsch215** [comment]
It is working in Chrome. I tried on Chrome with an earlier example and got error but it is working for all files now. Thanks!

**Comment by rsch215** [comment]
@mbabaian I cannot open .svg files in Chrome without opening it in Edge first and copying the address into Chrome. Is there a way to add Chrome to the list of apps used to open my .svg files?

**Comment by ehmatthes** [comment]
Can you use Ctrl-O in Chrome to open the file?

**Comment by rsch215** [comment]
Ctrl-O works, Thanks!
