### ISSUE TITLE
Pip3 has been successfully installed, but the pygame installation prompt failed

### ISSUE THREAD

**Issue by tingsky9985** [ehmatthes/pcc#33]
Hello

Currently installing pygame encounters a problem:
Pip3 has been successfully installed, but pygame can not be installed
Google some of the solutions, but did not solve this problem.
The use of python3 failed to install; python2.7 was installed successfully.

ting@ting-All-Series:~$ sudo pip3 install --user hg+http://bitbucket.org/pygame/pygame
The directory '/home/ting/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ting/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting hg+http://bitbucket.org/pygame/pygame
  Cloning hg http://bitbucket.org/pygame/pygame to /tmp/pip-i07ajklr-build
    Complete output from command python setup.py egg_info:
    
    
    WARNING, No "Setup" File Exists, Running "config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    
    Hunting dependencies...
    WARNING: "freetype-config" failed!
    SDL     : found 1.2.15
    FONT    : found
    IMAGE   : found
    MIXER   : found
    PNG     : found
    JPEG    : found
    SCRAP   : found
    PORTMIDI: found
    PORTTIME: found
    FREETYPE: not found
    Missing dependencies
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-i07ajklr-build/

=========================
ting@ting-All-Series:~$ pip3 --version
pip 9.0.1 from /usr/local/lib/python3.4/dist-packages (python 3.4)

**Comment by ehmatthes** [comment]
Hi @tingsky9985, are you still having this issue?
