### ISSUE TITLE
Black Square instead of ship.bmp

### ISSUE THREAD

**Issue by ivan-monge1989** [ehmatthes/pcc#35]
I am at ship.py and wrote the instruction self.image = pygame.image.load('images/ship.bmp'). I do not get any error but when I run the script, I just get a black square at the bottom of the screen instead of the ship.bmp. Any ideas? Am I missing any packages to be installed?

**Comment by ehmatthes** [comment]
Hi @ivan-monge1989, are you still having this issue? Are you on OSX?
