### ISSUE TITLE
runing django TemplateDoesNotExist

### ISSUE THREAD

**Issue by FarAwaytarget** [ehmatthes/pcc#36]
Hello I am learning 19 chapters, the emergence of the error 'TemplateDoesNotExist', I see a lot of some of the instructions, or did not solve the problem, you can help me see where is not set up, thank you so much, the following is the log

``

Request Method: | GET
-- | --
http://127.0.0.1:8000/new_topic/
1.11.3
TemplateDoesNotExist
learning_logs/new_topics.html
/usr/local/lib/python3.6/site-packages/django/template/loader.py in get_template, line 25
/usr/local/opt/python3/bin/python3.6
3.6.1
['/Users/Wzd/Documents/github/python/mydjango/project_1/learing_log',  '/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python36.zip',  '/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6',  '/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload',  '/Users/Wzd/Library/Python/3.6/lib/python/site-packages',  '/usr/local/lib/python3.6/site-packages']
Tue, 25 Jul 2017 14:29:17 +0000
`Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/new_topic/

Django Version: 1.11.3
Python Version: 3.6.1
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'learning_logs']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Template loader postmortem
Django tried loading these templates, in this order:

Using engine django:
    * django.template.loaders.filesystem.Loader: /Users/Wzd/Documents/github/python/mydjango/project_1/learing_log/learning_logs/templates/learning_logs/new_topics.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.6/site-packages/django/contrib/admin/templates/learning_logs/new_topics.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.6/site-packages/django/contrib/auth/templates/learning_logs/new_topics.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /Users/Wzd/Documents/github/python/mydjango/project_1/learing_log/learning_logs/templates/learning_logs/new_topics.html (Source does not exist)

Traceback:

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/Wzd/Documents/github/python/mydjango/project_1/learing_log/learning_logs/views.py" in new_topic
  46.     return render(request, 'learning_logs/new_topics.html', context)

File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py" in render
  30.     content = loader.render_to_string(template_name, context, request, using=using)

File "/usr/local/lib/python3.6/site-packages/django/template/loader.py" in render_to_string
  67.         template = get_template(template_name, using=using)

File "/usr/local/lib/python3.6/site-packages/django/template/loader.py" in get_template
  25.     raise TemplateDoesNotExist(template_name, chain=chain)

Exception Type: TemplateDoesNotExist at /new_topic/
Exception Value: learning_logs/new_topics.html`

**Comment by FarAwaytarget** [comment]
Can someone help me?

**Comment by ehmatthes** [comment]
Hi @FarAwaytarget, sorry to take a bit to get to this. Have you figured it out yet?

If not, it's saying that it can't find your template for the new_topic page. I notice some references in your logs to 'new_topics.html', with an s. There should only be new_topic, not new_topics. Is that what's causing the error?
