### ISSUE TITLE
print command on page 67

### ISSUE THREAD

**Issue by AndyJohnsonFinancialAnalyst** [ehmatthes/pcc#37]
whenever I perform the exercise foods.py page 67 it prints the commands separately instead of in a group, i.e. it prints "my favorite foods are:" right after I type the print command instead of in a block of text with the foods like stated in the book.
[Doc1.docx](https://github.com/ehmatthes/pcc/files/1188696/Doc1.docx)
 how do i fix that?

**Comment by ehmatthes** [comment]
It looks like you're only working in a python terminal session. Have you set up a text editor yet?
