### ISSUE TITLE
pygame installed but not import

### ISSUE THREAD

**Issue by Airmacho** [ehmatthes/pcc#38]
Hi, Eric:

I am using MacOS, and run those instructions already
~~~ bash
brew install hg sdl sdl_image sdl_ttf
brew install sdl_mixer portmidi
pip3 install --user  hg+http://bitbucket.org/pygame/pygame
~~~
after this, when I switch to python3 console, `import pygame`, no module named 'pygame'

below is the screenshoot:
<img width="640" alt="screen shot 2017-08-12 at 14 29 36" src="https://user-images.githubusercontent.com/7590312/29238567-d997ce74-7f6a-11e7-85a6-ce6c3f0bd8c8.png">

**Comment by ehmatthes** [comment]
Hi, sorry I just saw this. Have you sorted this out yet?

If not, I wonder if you have more than one version of Python 3.6 installed? It looks like you installed Anacaonda. It looks like you might have a Python 3.6 through Homebrew, and another instance of Python 3.6 through Anaconda.

Let me know and I'll help you troubleshoot.
