### ISSUE TITLE
About "K_SPACE" in game_functions.py in chapter 12 is not working in some keyboard

### ISSUE THREAD

**Issue by soolaugust** [ehmatthes/pcc#39]
When I tested alien game in chapter 12, I found "K_SPACE" is not working with my keyboard, so I change it to "K_UP", and it works fine. And after I check, I think the reason is "K_SPACE" is duplicated with some keyboard. So please modify it to clarify this phenomenon.thanks.

**Comment by ehmatthes** [comment]
Thank you for bringing this to my attention. It seems to be an issue with some keyboards which don't handle simultaneous key presses well. It sounds like you figured out a good solution.

Please let me know if you run into any other issues.
