### ISSUE TITLE
There is an error occur in test_survey.py in Chapter 11 

### ISSUE THREAD

**Issue by ShuaiDa** [ehmatthes/pcc#42]
**Dear Matthes:**

Thanks for your book  "**Python Crash Course**"!

I have learned a lot from it through coding. And I find out **an error occur in test_survey.py in Chapter 11.**

First I coded it by myself, but the Ipython console display "Failed". Then I search the Internet to find the answer.

When I find your code in Github, and run the code. The Ipython console **also** displays the same error as follows:

![image](https://user-images.githubusercontent.com/24203675/30946941-649f1d40-a439-11e7-811b-e2d7c92d3329.png)

The **paradox** is that when I run the language_survey.py, the Ipython console display the right result.

**Comment by ehmatthes** [comment]
This looks like a typo? But I think you've moved on from this. :)
