### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by EasonPy** [ehmatthes/pcc#46]
Dear Eric Matthes:
Thank you for this book.I like it very much!
But when i try to add a new topic,just like Chapter 19,but i failed because of 403 forbidden.
It seems something wrong in  {% csrf_token %}.
Can you help me to solve this problem?
With pleasure.

**Comment by ehmatthes** [comment]
Hi @EasonPy, can you post your code somewhere? You can make a github repository and point me to it, or you can email me. ehmatthes@gmail

**Comment by EasonPy** [comment]
@ehmatthes 
Sorry,I am a Chinese student.And i finished my exam today.I'm sorry about replying you so slowly.
I had written my email already. Is there anything wrong in the email address?The email website tells me the address is invalid. I cannot send my email to you, sir.

**Comment by ehmatthes** [comment]
Did you put a .com on the end of the email?

**Comment by EasonPy** [comment]
Oh,i think it will be a .us or another things.
Sorry,i will send my email to you after finishing my homework .
