### ISSUE TITLE
chapter 12 code does not work on os x within a virtualenv

### ISSUE THREAD

**Issue by haibin** [ehmatthes/pcc#49]
Just want to make a note that the chapter 12 code does not work on os x within a virtualenv.

https://bitbucket.org/pygame/pygame/issues/203/window-does-not-get-focus-on-os-x-with

**Comment by yangadam** [comment]
It may help to run the application with pythonw instead of python. (See [this](https://stackoverflow.com/a/9706045) to find out the difference.)

Or you would like to get help from #19.

**Comment by ehmatthes** [comment]
Hi @haibin, I just saw this. Are you still having an issue with this? Also, I just started testing more thoroughly on a mac and I noticed some speed issues. If you're running into any issues with the game going really slowly, please reach out on twitter @ehmatthes, or email ehmatthes@gmail.

**Comment by Javier-Chavez97** [comment]
I have been having this same issue and I have not found a fix for it. I can't get my window to change in any way.

**Comment by ehmatthes** [comment]
@Javier-Chavez97, do you need to run this within a virtualenv? Making games with pygame is one of the cases where virtualenvs don't always seem necessary.

If you're developing a web app, you're probably developing a few, and you want to keep the different app environments isolated. If you're only developing one or a few games, and they're all running on the same version of Pygame, virtualenvs aren't really necessary.

If you don't have an issue with installing pygame to your system, I'd just pip install pygame to the system, and work in a standard directory outside of any virtual environment. Does that approach work for you?
