### ISSUE TITLE
Freetype missing

### ISSUE THREAD

**Issue by loukasmaki** [ehmatthes/pcc#50]
In chapter 12 when you are supposed to install pygame (did this on both ubuntu 17.10 and 18.04) and you come to pip3 install --user hg+http://bitbucket.org/pygame/pygame

It complains that freetype is missing. So I had to also install libfreetype6-dev also. Then it works.

**Comment by ehmatthes** [comment]
On most recent versions of linux, you can use pip to install pygame directly:

`$ pip install --user pygame`

This should address any needed dependencies.
