### ISSUE TITLE
namespacing in learning_log\urls.py

### ISSUE THREAD

**Issue by mbburnett88** [ehmatthes/pcc#51]
Hi Eric,

The only way I could get this to work was by taking out the namespace argument, which you say on page 413 is important to know how to implement when projects start to grow. Please help me structure learning_log\urls.py so that I can use namespacing.

This one works (in that the server starts up)

from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('learning_logs.urls')),
]

System check identified no issues (0 silenced).
April 24, 2018 - 12:22:41
Django version 2.0.4, using settings 'learning_log.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

=================================

This fails...

from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
]

  File "C:\Users\mburnett\PycharmProjects\untitled\learning_log\learning_log\urls.py", line 7, in module>
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
  File "C:\Users\mburnett\PycharmProjects\untitled\learning_log\11_env\lib\site-packages\django\urls\conf.py", line 39, in include
    'Specifying a namespace in include() without providing an app_name '
django.core.exceptions.ImproperlyConfigured: Specifying a namespace in include() without providing an app_name is not supported. Set the app_name attribute in the included module, or pass a 2-tuple containing the list of patterns and app_name instead.

It's asking for an "app_name," but I don't know where that attribute should be set.

Here is the other urls.py file as it exists in learning_logS

"""Defines url patterns for learning_logs."""

from django.conf.urls import url
from . import views

urlpatterns = [
    # Home page.
    url(r'^$', views.index, name='index'),
    
    # Show all topics.
    url(r'^topics/$', views.topics, name='topics'),
    
    # Detail page for a single topic.
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
]

Thanks!

**Comment by mbburnett88** [comment]
I got this to work by adding "app_name = 'learning_logs' to the ...learning_logs\urls.py file and adding namespace='learning_logs' back as the second argument in the include statement.

https://stackoverflow.com/questions/14892462/django-error-upolls-is-not-a-registered-namespace

...learning_log\learning_logs\urls.py ....

"""Defines url patterns for learning_logs."""

from django.conf.urls import url
from . import views

app_name = 'learning_logs
urlpatterns = [
    # Home page.
    url(r'^$', views.index, name='index'),
    
    # Show all topics.
    url(r'^topics/$', views.topics, name='topics'),
    
    # Detail page for a single topic.
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
]

==============================

...\learning_log\learning_log\urls.py ....

from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
]

**Comment by ehmatthes** [comment]
Hi, there's a full writeup of updates related to Django 2.0 [here](http://ehmatthes.github.io/pcc/chapter_18/README.html#updates). The latest printing of the book has these updates in the text.

I will look at this more closely tonight, but I think the updates in the link address this issue.

Edit: I think the link should address this effectively; if there's anything unclear in that link please let me know.

**Comment by mbburnett88** [comment]
The author clearly posted this in his chapter notes. The issue is presented in the overview and the specifics are described in the section called "p. 413, Mapping a URL"

http://ehmatthes.github.io/pcc/chapter_18/README.html#updates

Thanks for the follow-up, Eric. Love the book!
