### ISSUE TITLE
"Message": "Not Found"

### ISSUE THREAD

**Issue by PatrickLittlefield** [ehmatthes/pcc#56]
ref p.378:
Upon entering the following address in my browser's address bar (Google Chrome):
https://api.github.com/search/respositories?q=language:python&sort=stars

I'm getting the following message:
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}

Please accept my advance apologies if this is some error on my part.

**Comment by ehmatthes** [comment]
Hi @PatrickLittlefield, I'm not sure if you've sorted this out already, but you have a typo in your url. You wrote "respositories", with an extra s before the p. Take that s out and things should be working!
