### ISSUE TITLE
'ascii' codec can't encode character '\u2013'

### ISSUE THREAD

**Issue by ghost** [ehmatthes/pcc#58]
This error appears on many of the files, I've been going around this problem by not calling the keys and values of the dictionary that are not correctly formatted

**Comment by thiagogcarmo** [comment]
You can try the follow Python String encode() Method:
anything_string.encode('utf-8')

**Comment by ghost** [comment]
@thiagogcarmo Thank you! both data types, strings and integers, have formatting errors. I fixed the strings though, thanks!
