### ISSUE TITLE
<!DOCTYPE html> - Unexpected tokens

### ISSUE THREAD

**Issue by runnerpaul** [ehmatthes/pcc#59]
On Chapter 20, when I edit base.html I get an error at <!DOCTYPE html>. It says "Unexpected tokens".

Do you know how to fix this?

**Comment by ehmatthes** [comment]
Sorry, I'm just seeing this. What changes are you making to base.html?

**Comment by runnerpaul** [comment]
@ehmatthes this can be closed. I can't remember what trhe resolution was but I got it fixed. Most likely a typo or something. Close #59.

**Comment by ehmatthes** [comment]
Okay, thanks!
