### ISSUE TITLE
Chapter 12 - problem with installing the Pygame

### ISSUE THREAD

**Issue by DominikWhite** [ehmatthes/pcc#67]
Hi Eric,

I am using MacOS 10.14 and I have a problem with installing Pygame.

After running those codes in Terminal:

> brew install hg sdl sdl_image sdl_ttf
> brew install sdl_mixer portmidi
> pip3 install --user  hg+http://bitbucket.org/pygame/pygame

Everything is going well except the last code (pip3 installer).

See the screenshot below:
<img width="571" alt="screenshot 2018-09-30 at 19 04 56" src="https://user-images.githubusercontent.com/43641932/46260244-bf3f0a00-c4e3-11e8-811d-d53869175189.png">
 
Do you know what could be the problem here?

Thank you in advance!

**Comment by ehmatthes** [comment]
Pygame can usually be installed straight through pip now. What happens if you run this:

$ python3 -m pip install --user pygame

I'm assuming you use the command python3 for the 3.7 installation, and that python still points to the 2.7 that came with your Mac?

**Comment by DominikWhite** [comment]
Yes, you're right! My Mac was pointing the 2.7.

After running your command I've got the response that "Requirement already satisfied(...)".

So the original problem was that I assumed that Pygame is not installed because of the error in the attempt to launch the Pygame window.

I used the script from your book as follows:

    import sys
    import pygame
    def run_game():
        # Initialize game and create a screen object.
        pygame.init()
        screen = pygame.display.set_mode((1200, 800))
        pygame.display.set_caption("Alien Invasion")
        # Start the main loop for the game.
        while True:
            # Watch for keyboard and mouse events.
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    sys.exit()
            # Make the most recently drawn screen visible.
            pygame.display.flip()
    run_game()

And I got an error:

    Traceback (most recent call last):
      File "/Users/bielas/Desktop/Python Crash Course/alien_invasion/alien_invasion.py", line 3, in <module>
        import pygame
    ModuleNotFoundError: No module named 'pygame'

Do you have any ideas why I've got an error connected with opening Pygame window?

Thank you for your fast response and a great book!

**Comment by DominikWhite** [comment]
I found the solution.

The problem was connected with the interpreter used in PyCharm. Pycharm automatically was using the interpreter created with the project. Unfortunately, that interpreter didn't consist of Python with Pygame installed on it. After switching the interpreter into general Python 3.7 the problem was gone.

Thank you again for your help!
