### ISSUE TITLE
Thanks for using django-bootstrap3

### ISSUE THREAD

**Issue by dyve** [ehmatthes/pcc#68]
Hi @ehmatthes, just wanted to thank you for your trust in https://github.com/dyve/django-bootstrap3! Great to see it in your book.

**Comment by ehmatthes** [comment]
You're so welcome! I can't thank you enough for making that available.

Readers have loved the Djano project in the book, and I think a good part of that has to do with how easily they can make a professionally-styled project even though they're just getting started as programmers.
