### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by VerosK** [ehmatthes/pcc#70]
Hello, 

I would like to use these cheat sheets for my Python class, but this GitHub repository is missing license. I'm not sure whether I can use these files or not.

May I ask you to add some LICENSE file to the repository?

Thank you very much for your work.

**Comment by ehmatthes** [comment]
Hi, I won't get to a license today, but you are quite welcome to use the cheat sheets in a class. The sheets have a reference to this book, and that's all the attribution that's needed.

**Comment by VerosK** [comment]
Thank you very much.
