### ISSUE TITLE
ch12 somewhere i don't understand,please help me!

### ISSUE THREAD

**Issue by xiaomaofeng** [ehmatthes/pcc#73]
in the ch12,ship.py
the self.rect.centerx only stores the integers,so must change it to float,
so use self.center to instead,
but in the line 35:self.rect.centerx = self.center,
why centerx can store in float in this time?
i don't understand,please tell me,thank you sincerely!

**Comment by ehmatthes** [comment]
Hi,

In this line:

    self.rect.centerx = self.center

centerx isn't storing a float. It's keeping the integer part of the float that's stored in self.center. Let's say you had a ship speed of 1.5. Here's how the values of self.center and self.rect.centerx might evolve:

    self.center    self.rect.centerx
    200.0            200
    201.5            201
    203.0            203
    204.5            204
    206.0            206

Is this helpful? If so, you can add some print() calls to your code that lets you see real-time values in your game:

    print(self.center, self.rect.centerx)

If you put this at the end of the Ship.update() method, you'll see how these values change as you move the ship. Just take the print() calls out, or comment them out, when you're done so they don't slow the game down.

Is that helpful?

**Comment by xiaomaofeng** [comment]
hello!
thank you very much for your reply.
now i understand why this is necessary.
it helps me a lot.
thank you very much!

**Comment by ehmatthes** [comment]
You're welcome!
