### ISSUE TITLE
Chapter 18 urls.py incompatible with Django2

### ISSUE THREAD

**Issue by andysw90** [ehmatthes/pcc#74]
As described [here](https://stackoverflow.com/questions/43324005/django-deprecation-warning-or-improperlyconfigured-error-passing-a-3-tuple-to) and [here](https://code.djangoproject.com/ticket/28631), and elsewhere the url in ./learning_log/learning_log/urls.py no longer accepted the include argument 3-tuple. Instead the syntax regex argument and app name should be passed.

**Comment by andysw90** [comment]
https://docs.djangoproject.com/en/1.11/releases/1.9/#passing-a-3-tuple-or-an-app-name-to-include

**Comment by ehmatthes** [comment]
Thank you for bringing this up. I have updated the book each time it's gone out for a new printing, so I believe the latest printings of the book address this issue, and have for some time.

The [online updates](http://ehmatthes.github.io/pcc/updates.html) for this project show how the project should be modified for people who are working from an older copy of the book. Also, there is a complete working version of the Learning Log project for Django 2.0 and Django 2.1 in the [chapter 20 online resources](https://github.com/ehmatthes/pcc/tree/master/chapter_20).
