### ISSUE TITLE
chapter17 python_repos.py 

### ISSUE THREAD

**Issue by ChenBin113** [ehmatthes/pcc#77]
Hello, I run your code meet some problems.

The last line of code:
chart.render_to_file('python_repos.svg')

In Windows10, pycharm environment run to get:
'NoneType' object has no attribute 'decode'

So I change something to run that, but I don't know exactly how it works, the code is:
chart.render_to_file('python_repos.svg', decode='utf-8')

Thank you!

**Comment by ehmatthes** [comment]
I'm not clear if you still have a question. Did your modification work?

**Comment by ChenBin113** [comment]
Yes, the problem is solved, but I don't know why I change the code like this 
chart.render_to_file('python_repos.svg', decode='utf-8')
can work successful?

**Comment by ehmatthes** [comment]
There's a character in one of the fields that Pygal is trying to render, but it can't. When you add the specific decoding argument 'utf-8', it knows what to do with that character. I imagine it's an emoji used in a project description.
