### ISSUE TITLE
Chapter 10. Task 10-6. Addition.

### ISSUE THREAD

**Issue by TheFuzzStone** [ehmatthes/pcc#80]
Hi @ehmatthes!
Thank very much for really awesome book! 

I think I found an error.

Chapter 10: "**Files and Exceptions**" we have a task 10-6:

---

_10-6. Addition: One common problem when prompting for numerical input
occurs when people provide text instead of numbers. When you try to convert
the input to an int, you’ll get a **TypeError**. Write a program that prompts for
two numbers. Add them together and print the result. Catch the TypeError if
either input value is not a number, and print a friendly error message. Test your
program by entering two numbers and then by entering some text instead of a
number._

---

But if "user" enter a text and the program try convert it we get a **ValueError**.

**Comment by ehmatthes** [comment]
Hi,

This has been changed to ValueError in later printings, but thank you for
letting me know.

Eric
