### ISSUE TITLE
Several interface changed in python.

### ISSUE THREAD

**Issue by jyj407** [ehmatthes/pcc#83]
`pygal.Worldmap(style=wm_style)` is outdated, probably should be `pygal.maps.world.World(style=wm_style)`

`pcc/chapter_16/country_codes.py` outdated as well.
The module name should be `from pygal.maps.world import COUNTRIES` now.
Even that, when I run the program, only the first country cannot be  found.

```
$ python country_codes.py
ad
None
None
```

**Comment by ehmatthes** [comment]
I'm closing all old issues. Sorry I did not see this earlier. If you'd still like help, please feel free to comment or reopen the issue, and I should get a notification and be able to help.
