### ISSUE TITLE
Chapter 19 -       cannot import name 'login' from 'django.contrib.auth.views'

### ISSUE THREAD

**Issue by Derif** [ehmatthes/pcc#86]
Working through the book, first edition.  The second edition was released about 3 weeks after I ordered and received this.

Found discussion here: https://stackoverflow.com/questions/51906428/django-cannot-import-login-from-django-contrib-auth-views

Seems that the method used in book was already deprecated for django-2.0 and phased out for django-2.1.

~~I see it fixed in chapter 20 and will adapt from there.~~  It might be worthwhile updating the notes you have for Chapter 19 however.

I'm attempting to downgrade to Django 2.0.

**Comment by HotcakesSanderson** [comment]
from django.contrib.auth.views import LoginView

from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
  path('login/', LoginView.as_view(template_name='users/login.html'), name="login"),
  path('logout/', views.logout_view, name='logout'),
  path('register/', views.register, name='register'),
]
 No need to downgrade. I found the same issue and imported LoginView
