### ISSUE TITLE
chapter_14/button.py

### ISSUE THREAD

**Issue by fizzzzzzzz** [ehmatthes/pcc#87]
Hi！
Thank you very much for this awesome book!

I have a question for the function parameter.

def __init__(self, ai_settings, screen, msg):

“ai_settings” is not used in the code. Why should add it to the parameter?

I'm sorry, my English is bad. Hope you understand what I said.

**Comment by ehmatthes** [comment]
I'm closing all old issues. Sorry I did not see this earlier. If you'd still like help, please feel free to comment or reopen the issue, and I should get a notification and be able to help.
