### ISSUE TITLE
learning_logs.url preventing server from starting

### ISSUE THREAD

**Issue by thumble** [ehmatthes/pcc#89]
Ch18 of the book
    path('', include('learning_logs.url')),

ModuleNotFoundError: No module named 'learning_logs.url'

is breaking the server. any alternatives?

**Comment by ehmatthes** [comment]
I'm closing all old issues. Sorry I did not see this earlier. If you'd still like help, please feel free to comment or reopen the issue, and I should get a notification and be able to help.
