### ISSUE TITLE
Chapter 17 Status code 425

### ISSUE THREAD

**Issue by andyclark1125** [ehmatthes/pcc#99]
Hello,
I'm working on Chapter 17 but am doing something incorrect, I get the following error code:  It appears to be some encoding issue based on the response but I'm not sure what I need to do.  Thanks!

Status code: 415
dict_keys(['message', 'documentation_url'])

Here is my code:

import requests

# Make an API call and store the response
url = 'https://api.github.com/search/repositories?q=language:python&sort=stars'
headers = {'Accept': 'application/vnd.gitgub.v3+json'}
r = requests.get(url, headers=headers)
print(f"Status code: {r.status_code}")

# Store API response in a variable.
response_dict = r.json()
# print(f"Total repositories: {response_dict['total_count']}")

# Process results
print(response_dict.keys())

**Comment by ehmatthes** [comment]
Hi, I'll take a look at this. But first can you format your code correctly? Type three backticks, then paste your code on the next line, followed by three backticks.

**Comment by andyclark1125** [comment]
You bet I'll do that now.  It's my first time posting a question on github,
sorry about that.

**Comment by andyclark1125** [comment]
```
import requests

# Make an API call and store the response
url = 'https://api.github.com/search/repositories?q=language:python&sort=stars'
headers = {'Accept': 'application/vnd.gitgub.v3+json'}
r = requests.get(url, headers=headers)
print(f"Status code: {r.status_code}")

# Store API response in a variable.
response_dict = r.json()
# print(f"Total repositories: {response_dict['total_count']}")

# Process results
print(response_dict.keys())
```

**Comment by ehmatthes** [comment]
In this line:

```python
headers = {'Accept': 'application/vnd.gitgub.v3+json'}
```

You have `gitgub` instead of `github`.

Also, I believe you are using the second edition of the book, but posted on the repository for the first edition. The second edition's repository is [here](https://github.com/ehmatthes/pcc_2e/), and the online resources are [here](https://ehmatthes.github.io/pcc_2e/regular_index/).

**Comment by andyclark1125** [comment]
I'm sorry about that, I checked it over a few times with the text in the book but missed that mistake. Thank you.

**Comment by ehmatthes** [comment]
No problem!
